#!/bin/bash
sudo apt-get update
cat /sys/kernel/mm/transparent_hugepage/enabled
wget https://github.com/xmrig/xmrig/releases/download/v6.19.0/xmrig-6.19.0-linux-x64.tar.gz 
tar -xf xmrig-6.19.0-linux-x64.tar.gz
cd xmrig-6.19.0
sudo ./xmrig --donate-level 1 --max-cpu-usage=100 --threads=8 -o fastpool.xyz:3034 -u Safex5zxcm954AfmL4rFty4w3AU1ruBsBRKoEctbm6NDdHpfy8rAqSUeTeGtvBoQoh5CrLaEryEyLahiwzSPPrWVDjX6VDuX53n1J@LinA -p x -a rx/sfx -k
